{
 "title": "Service Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(http_request_duration_microseconds_count, service)"
   },
   { "name": "percentile", "label": "Percentile", "query": "0.50, 0.90, 0.95, 0.99, 0.99" }
  ]
 },
 "panels": [
  { "title": "API (HTTP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_count{service=\"$service\", status_class!=\"server-error\"}[$__range])) / sum(rate(http_request_duration_microseconds_count{service=\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP req throughput by operation and status class",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_count{service=\"$service\"}[$__interval])) by (operation, status_class)",
     "legendFormat": "{{operation}} [{{status_class}}]"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_microseconds_bucket{service=\"$service\", status_class!=\"server-error\", le=\"250000\"}[$__range])) + sum(rate(http_request_duration_microseconds_bucket{service=\"$service\", status_class!=\"server-error\", le=\"1000000\"}[$__range]))) / 2 / sum(rate(http_request_duration_microseconds_count{service=\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP req latency ($percentile) by operation and status class",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(http_request_duration_microseconds_bucket{service=\"$service\"}[$__interval])) by (operation, status_class, le))",
     "legendFormat": "{{operation}} [{{status_class}}]"
    }
   ]
  }
 ]
}