{
 "title": "Service Calls",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(http_request_duration_microseconds_count, service)"
   },
   {
    "name": "to_service",
    "label": "To service",
    "query": "label_values(service_call_duration_microseconds_count{service=\"$service\"}, to)"
   },
   { "name": "percentile", "label": "Percentile", "query": "0.50, 0.90, 0.95, 0.99, 0.99" }
  ]
 },
 "panels": [
  { "title": "$to_service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "to_service" },
  {
   "title": "Success rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(service_call_duration_microseconds_count{service=\"$service\", to=\"$to_service\", status_class!~\"server-error|error\"}[$__range])) / sum(rate(service_call_duration_microseconds_count{service=\"$service\", to=\"$to_service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Throughput by operation and status class",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_call_duration_microseconds_count{service=\"$service\", to=\"$to_service\"}[$__interval])) by (operation, status_class)",
     "legendFormat": "{{operation}} [{{status_class}}]"
    }
   ]
  },
  {
   "title": "Latency ($percentile) by operation and status class",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(service_call_duration_microseconds_bucket{service=\"$service\", to=\"$to_service\"}[$__interval])) by (operation, status_class, le))",
     "legendFormat": "{{operation}} [{{status_class}}]"
    }
   ]
  }
 ]
}